name: Pull Request Checks

on:
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - uses: actions/setup-node@2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn lint
      - run: yarn tsc
